### ISSUE TITLE
Inheriting from a Base class fails

### ISSUE THREAD

**Issue by jufemaiz** [joker1007/activemodel-associations#3]
Hi, thanks for the work. To DRY my code, I created a base class:

```
class Star < ActiveRecord::Base
end

require 'active_model'

class Awesome::Base
  extend ActiveModel::Naming
  extend ActiveModel::Callbacks
  include ActiveModel::Model
  include ActiveModel::Associations
  include ActiveModel::Conversion
  include ActiveModel::Dirty
  include ActiveModel::Validations
  
  # need hash like accessor, used internal Rails
  #
  # @param attr [?] blah
  # @return ?
  def [](attr)
    self.send(attr)
  end

  # need hash like accessor, used internal Rails
  #
  # @param attr [?] blah
  # @return ?
  def []=(attr, value)
    self.send("#{attr}=", value)
  end

end
```

Now, I want to have:

```
class Awesome::Planet < Awesome::Base
  belongs_to :star
end
```

However I'm getting the following:

```
NoMethodError: undefined method `[]' for nil:NilClass
	from /.../gems/activemodel-associations-0.1.0/lib/active_model/associations/override_methods.rb:96:in `association_instance_get'
	from /.../gems/activemodel-associations-0.1.0/lib/active_model/associations/override_methods.rb:57:in `association'
	from /.../gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:115:in `star'
	from (irb):3
	from /.../gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /.../gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /.../gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /.../gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /.../gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

The @association_cache is not being initialized (staying as nil, haence the "undefined method '[]'" issue).

Any thoughts?

**Comment by joker1007** [comment]
@jufemaiz 
I see.
I got same result when use subclass.
Thanks for your report!! :smile: 
I try to fix it.

**Comment by joker1007** [comment]
@jufemaiz 
What version ruby are you use?
If you use ruby-1.9.x, sorry, this gem does'nt support it.
this gem use `Module#prepend` internally.

**Comment by jufemaiz** [comment]
Ruby 2.1.2

**Comment by joker1007** [comment]
Sorry,
I tried to execute your code, but That exception was not raised.
I don't know cause of this probrem.
Please tell me more information about your environment.
